Enhance order importer
solidusio-contrib/solidus_importer pull request #39
Opened 2020-09-25 10:45 UTC by MinasMazar

The approach used to generate entities whenever they're encountered during CSV row parsing works well with Customers and Products models, but has some downside whe importing orders. This is bebause the models involved have more constraints and validations on models and associated models, and you could end up having entities in inconsistent state. For this reason we've decided to take advantage of the Solidus order importer](https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/importer/order.rb): order's processors won't create entities anymore, but are responsible to build the data structure needed by the aforementioned importer, which actually creates orders. The importer is invoked after the whole CSV is parsed, in the `#after_import` callback defined in a custom `OrderImporter` which extend the `Base` importer used by other types (customers, products).

2020-09-25 15:29 UTC, elia requested changes
A few suggestions and questions

2020-10-09 08:46 UTC, MinasMazar commented on lib/solidus_importer/order_importer.rb
> +      Spree::Config.tax_adjuster_class = previous_adjuster
I've opted in for an _override solution_ (check [`62d596e`](https://github.com/solidusio-contrib/solidus_importer/pull/39/commits/62d596e546911347630d4bc1a553203bf043229e) and [`d6f00d7`](https://github.com/solidusio-contrib/solidus_importer/pull/39/commits/d6f00d74ac4cf728bee2757986f737ef7fba8b3c)). Do you see any downsides with this approach?

2020-10-09 15:40 UTC, elia commented on lib/solidus_importer/order_importer.rb
> +      Spree::Config.tax_adjuster_class = previous_adjuster
Looks great thanks!

2020-10-09 15:40 UTC, elia approved these changes

2020-10-09 15:40 UTC, merged