Check for duplicated option values and avoid adding them
solidusio-contrib/solidus_importer pull request #76
Opened 2021-08-17 20:28 UTC by vdanciu

When the import file has more lines for each variant in order to
specify more images per variant the mapping to the variant is made
through options instead of variant sku (which is optional). As a
result of repeating the options on all lines they are also added
by the importer multiple times ending. This change avoids adding
them if already present.

2021-08-17 20:42 UTC, jarednorman requested changes
You don't need to open a new PR; you can amend/rebase the existing commits and force push your branch so we can keep the conversation about the change all together.

2021-08-17 20:42 UTC, jarednorman commented on spec/lib/solidus_importer/processors/option_values_spec.rb
> +require 'pry-byebug'
This shouldn't be included in this PR.

2021-08-17 20:42 UTC, jarednorman commented on Gemfile-local
> +gem 'pry-byebug'
This file shouldn't be included in this PR.

2021-08-17 20:42 UTC, jarednorman commented on .gitignore
> +Gemfile-local
This is a good change, but belongs in its own commit.

2021-08-18 06:41 UTC, vdanciu commented
> You don't need to open a new PR; you can amend/rebase the existing commits and force push your branch so we can keep the conversation about the change all together.

My git skills are abysmal. I was working on something else in the meantime and my master branch moved forward with new changes so I created a branch only for this and did not know how to amend a PR from having vdanciu/master as source to having vdanciu/duplicated-options as source and since I was short on time I just closed it.

Thank you for your patience. I removed the extra changes I forgot in the PR (for debugging).

2021-08-18 21:24 UTC, jarednorman approved these changes
Thanks. This all looks good to me!

2021-08-31 08:10 UTC, kennyadsl approved these changes
Thanks!

2021-08-31 08:10 UTC, merged